# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  test:
    if: github.event.action != 'closed' || github.event.pull_request.merged

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: 'Install Poetry'
      run: |
        python -m pip install poetry
        poetry config virtualenvs.create false

    - run: poetry install

    - run: pytest tests

    - run: mypy --ignore-missing-imports release_often/

    - run: black --check .


  release:
    needs: [test]
    if: github.event_name == 'pull_request' && github.ref == 'master' && github.event.action == 'closed' && github.event.pull_request.merged

    runs-on: ubuntu-latest

    steps:

    - uses: brettcannon/release-often@master
      with:
        changelog-path: CHANGES.md
        github-token: ${{ secrets.GITHUB_TOKEN }}
